### ISSUE TITLE
Issue in parse:extract function

### ISSUE THREAD

**Issue by dverac** [streetslab/dimelo_v2#12]
I have already run the parsing steps with the testing sets, as well as one of my samples with a large sets of regions in a bed in interactive sessions. 
I am using a Python script that contains only the two parsing functions, pileup and extract, so I can submit it as a regular slurm job.  In this case, my bed contains a single region, and the bam contains only the reads in the region of interest. I can get the pileup results but not the extract function results. Can you point toward what is likely the issue? Other than the reduced region of interest, I am using the same parameters (motifs and thresholds). 

Bam file: results/Hia5_cell_chr3_192899kb/region_mk.bam
Regions bed: results/Hia5_cell_chr3_192899kb/region.bed
Output directory: results/Hia5_cell_chr3_192899kb
Window size: 500
Threshold: 190
<class 'int'>
<class 'int'>
Allocating requested 1 cores.
Modification threshold of 190 assumed to be for range 0-255. 190/255=0.7450980392156863 will be sent to modkit.
██████████| Step 1 complete. Located ['A,0', 'CG,0'] in hg38.fa:  100% | 00:55
██████████| Step 2 complete. 0 contigs processed from region_mk.bam:  100% | 00:00<00:00
██████████| modkit pileup return code 0 | > Done, processed 463 rows. Processed ~6 reads and skipped zero reads.:  100%
[W::hts_idx_load3] The index file is older than the data file: results/Hia5_cell_chr3_192899kb/region_mk.bam.bai
[W::hts_idx_load3] The index file is older than the data file: results/Hia5_cell_chr3_192899kb/region_mk.bam.bai:  100%
Allocating requested 1 cores.
Modification threshold of 190 assumed to be for range 0-255. 190/255=0.7450980392156863 will be sent to modkit.
██████████| Step 1 complete. Located ['A,0'] in hg38.fa:  100% | 00:53
██████████| Step 2 complete. 0 contigs processed from region_mk.bam:  100% | 00:00<00:00
██████████| modkit extract return code 0 | rocessed 6 reads, 816 rows, skipped ~0 reads, failed ~0 reads:  100%
Traceback (most recent call last):s processed:    0%                   
  File "h5py/h5t.pyx", line 1448, in h5py.h5t._c_int6 reads, 816 rows, skipped ~0 reads, failed ~0 reads:  100%
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/project/spott/dveracruz/plot_region/dimelo_parsing.py", line 127, in <module>
    extract_file, extract_regions = parse_bam.extract(
                                    ^^^^^^^^^^^^^^^^^^
File "/project/spott/dveracruz/bin/miniconda3/envs/dimelo_modkit_parsing/lib/python3.11/site-packages/dimelo/parse_bam.py", line 497, in extract
    read_by_base_txt_to_hdf5(
  File "/project/spott/dveracruz/bin/miniconda3/envs/dimelo_modkit_parsing/lib/python3.11/site-packages/dimelo/parse_bam.py", line 847, in read_by_base_txt_to_hdf5
    h5.create_dataset(
  File "/project/spott/dveracruz/bin/miniconda3/envs/dimelo_modkit_parsing/lib/python3.11/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/spott/dveracruz/bin/miniconda3/envs/dimelo_modkit_parsing/lib/python3.11/site-packages/h5py/_hl/dataset.py", line 86, in make_new_dset
    tid = h5t.py_create(dtype, logical=1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/h5t.pyx", line 1663, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1687, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1705, in h5py.h5t.py_create
  File "h5py/h5t.pyx", line 1459, in h5py.h5t._c_int
TypeError: Unsupported integer size (0)
srun: error: midway3-0129: task 0: Exited with exit code 1

**Comment by OberonDixon** [comment]
Can you run with `cleanup=False` and show me some of what your `pileup.sorted.bed` and `read.A,0.txt` files contain? The error suggests that when we are constructing our `reads.combined_basemods.h5`, we are passing some bad parameter(s) to our dataset creator which makes `h5py` throw an error. I don't think we should see an error if e.g. there are no valid `A,0` motifs with reported modification probabilities in any of the specified windows, but if the pileup and read files show something to that effect it will help nail down the cause here. 

I can't figure out currently how to reproduce the error above with `h5py.File.create_dataset`, so it could be worthwhile to also verify which version of h5py you have installed.

**Comment by dverac** [comment]
Thanks for the help, so the conda environment has **h5py version = 3.11.0**, **modkit 0.2.4**  I ran the extract function with cleanup = False (chr3:192898500-192899500), BAM containing reads extracted from the same region using samtools. 

head -n 3 pileup.sorted.bed (462 lines)
chr3    192898500       192898501       a,A,0   1       +       192898500       192898501       255,0,0 1 0.00 0 1 0 0 0 0 1
chr3    192898501       192898502       a,A,0   1       +       192898501       192898502       255,0,0 1 0.00 0 1 0 0 0 0 1
chr3    192898502       192898503       a,A,0   1       +       192898502       192898503       255,0,0 1 0.00 0 1 0 0 0 0 1

head -n 3 reads.A,0.txt (808 lines)
read_id forward_read_position   ref_position    chrom   mod_strand      ref_strand      ref_mod_strand  fw_soft_clipped_start   fw_soft_clipped_end     read_length     mod_qual        mod_code    base_qual        ref_kmer        query_kmer      canonical_base  modified_primary_base   inferred        flag
f3496a20-79a7-405e-b870-ee38990a0cf9    7492    192898523       chr3    +       +       +       75      52      12682   0.052734375     a       17      TAAAG   TAAAG   A       A       false   0
f3496a20-79a7-405e-b870-ee38990a0cf9    7493    192898524       chr3    +       +       +       75      52      12682   0.25195313      a       18      AAAGC   AAAGC   A       A       false   0

And reads.combined_basemods.h5 contains only the header HDF.

**Comment by OberonDixon** [comment]
Per our email communication, the issue was isolated to a numpy version incompatibility. The environment had installed both `numpy` and `numpy-base` with different major versions.

```
numpy                     2.0.1                    pypi_0    pypi
numpy-base                1.26.4          py311hbfb1bba_0    anaconda
```

When I recreated this configuration on my machine, I also saw an error. My error was more catastrophic, but further investigation suggested that `h5py` registers a specific numpy version, which might get handled different depending on how and in which order packages are installed. At line 847 in `parse_bam`, we currently implicitly set an integer dataset type using the `"i"` option, which may be better to set explicitly.

Meanwhile, however, I verified that without `numpy-base`, both `numpy 1.26.4` and `numpy 2.0.1` allow to complete end-to-end `extract` operation. @dverac has verified that when she removes `numpy-base` and uses `numpy 1.26`, she can also successfully run the full `pileup` and `extract` pipelines.
